export const products = [
  {
    id: 1,
    path: "/products/1.svg",
    title: "one",
    name: "Cudddle Hub",
    price: "#700,000",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "2",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 2,
    path: "/products/2.svg",
    title: "two",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 3,
    path: "/products/3.svg",
    title: "three",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 4,
    path: "/products/4.svg",
    title: "four",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 5,
    path: "/products/5.svg",
    title: "five",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 6,
    path: "/products/6.svg",
    title: "six",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 7,
    path: "/products/7.svg",
    title: "seven",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 8,
    path: "/products/8.svg",
    title: "eight",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 9,
    path: "/products/2.svg",
    title: "nine",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 10,
    path: "/products/1.svg",
    name: "Comfort King",
    title: "ten",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 11,
    path: "/products/4.svg",
    title: "eleven",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
  {
    id: 12,
    path: "/products/3.svg",
    title: "twelve",
    name: "Comfort King",
    price: "#340,00",
    dimension: "L-60cm, D-90cm, H-60cm",
    delivery: "2-3 working days(after payment confirmation",
    quantity: "6",
    desc: "Cuddle Hub is a piece of furniture typically used for seating one person comfortably.It typically consists of a cushiony seat and backrest, supported by a frame. Sofas come in various sizes, styles, and materials and can be a central element in living rooms, lounges, and other communal spaces. Cuddle Hub provide comfort, support, and can serve as an aesthetic statement piece in interior decorating.",
  },
];
